### PR TITLE
Change protocol name into `ObjObsSAP`

### PR DESCRIPTION
**Pull request by gmantele**
Following recent discussions about the name of this protocol, I took the liberty to rename this GitHub repository into `ObjObsSAP` (as well as its description). The former name `ObjVisSAP` should still work for Git operation (clone, pull, push, ...), but it is strongly recommended to change the URL of the remote repository in local clones with the following commands:

```bash
# 1. List all remote repository you have:
git remote -v

# 2. Find the one corresponding to `ivoa-std/ObjVisSAP` ; generally it is named `origin`

# 3. Update the URL of this remote repository:
git remote set-url origin git@github.com:ivoa-std/ObjObsSAP.git
```

Anyway, this PullRequest aims to propagate the name change inside the document itself and all related files. I tried to change this name (and its long form: Object Visibility into Object Observability) everywhere.

Please, make sure I did it well everywhere, especially in the examples where the URL of the (existing?) services included ObjVisSAP, as well as in the URI of the ObjObsSAP data model.

### CODE REVIEW

**Comment by molinaro-m** [comment]
Hi @gmantele : I find difficulties in building the doc, it seems to have something to do with the bibliography.

Besides that, the failure in autobuild is related to the version of upload-artifact (now @v4) and the preview I don't know (I have the same issue in ConeSearch)

Anyway, all the above is minor to me, while possibly I'd like to see a changelog for the doc name change, just for future reference. I would have suggested one in review but, without being able to compile first, I don't know where to start from.

**Comment by gmantele** [comment]
It should now be OK for the CI.

Your issue with the Cone Search should be solved the same way I did (the properties `tag-name` and `tag-description` should be put in lower case now with v2 of weareyipyip/walking-tag-action).

Anyway, I am not sure about the change log. It is the first version of this protocol and it is still a draft. I don't know if having a change log just for this name change is very useful :-/ If you want one anyway, I can add that. Do you have a suggestion?

**Comment by molinaro-m** [comment]
now, fine as it is...I have to fix something on my side, because I cannot make the doc on my machine, it errors out with 

`[15] (./ObjObsSAP.bbl`
`Runaway argument?`
`\parindent \z@ \bibpreamble \bibfont \list {\@biblabel {\the \c@NAT@ctr \ETC.`
`! Paragraph ended before \HD@@guesstoclevel was complete.`

**Review by molinaro-m — COMMENTED** [review]
fine with name change

**Pull request closed without merging**
